title: Franklin Cecilio Lopez Calderon
description: I am a quantitative economist with a strong foundation in econometrics, machine learning, and data-driven business analysis. My professional journey spans financial management, market regulation, and advanced analytics, where I have combined statistical rigor with practical business insight to support decision-making and drive measurable impact.
theme: jekyll-theme-minimal
